# Generated by Django 5.2.4 on 2025-09-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_passwordresettoken_user_userverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='system',
            field=models.CharField(choices=[('PHARMACY', 'Pharmacy'), ('SCHOOL', 'School')], max_length=20),
        ),
    ]
