# Generated by Django 5.2.4 on 2025-09-14 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sale_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('mobile', models.CharField(max_length=20)),
                ('operator_ref_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Raw PayChangu API response', null=True)),
                ('user_email', models.EmailField(blank=True, help_text="User's email for notifications", max_length=254, null=True)),
                ('subscription_plan', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], help_text='Selected subscription plan', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['charge_id'], name='core_subscr_charge__682838_idx'), models.Index(fields=['status'], name='core_subscr_status_a8bfa7_idx')],
            },
        ),
    ]
