# Generated by Django 5.2.4 on 2025-09-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sale_is_voided_sale_void_reason_sale_voided_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='is_voided',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='void_reason',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='voided_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='voided_by',
        ),
    ]
